# action.yml
name: 'Setup AWS elasticbeanstalk cli'

author: Tristan Barlow

description: 'Setup AWS elasticbeanstalk cli for use in all future steps'

branding:
  icon: 'terminal'  
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Install python 3
      run: sudo apt install python3.7
      shell: bash

    - name: Upgrade Pip
      run: pip3 install --upgrade setuptools pip
      shell: bash
    
    - name: export path
      run: export PATH="~/.local/bin:$PATH"
      shell: bash
      
    - run: pip3 install awsebcli --upgrade
      shell: bash

    - name: list path
      run: ls -al ~/.local/bin:$PATH
      shell: bash
