name: Run tests
on: 
  push:
    paths-ignore:
      - '*.md'
      - LICENCE

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print version
        uses: ./
        with:
          command: '--version'
